export default [
  {
    id: 'sto',
    label: 'СТО',
    icon: 'bi-shop',
    permission: 'sto.view',
    items: [
      { label: 'Список СТО',   to: '/sto',              icon: 'bi-list-ul',      permission: 'sto.view' },
      { label: 'Імпорт СТО',   to: '/sto/import',       icon: 'bi-cloud-download', permission: 'sto.view' },
      { label: 'Розсилка',     to: '/sto/outreach',     icon: 'bi-send',           permission: 'sto.view' },
      { label: 'Заявки',       to: '/sto/applications', icon: 'bi-person-check',   permission: 'sto.view' },
    ],
  },
  {
    id: 'users',
    label: 'Користувачі',
    icon: 'bi-people',
    permission: 'users.view',
    items: [
      { label: 'Список', to: '/users', icon: 'bi-list-ul', permission: 'users.view' },
      { label: 'Менеджери СТО', to: '/sto-managers', icon: 'bi-shield-lock', permission: '*' },
      { label: 'Адміністратори', to: '/admin-management', icon: 'bi-shield-check', permission: '*' },
      { label: 'Ролі та права', to: '/roles', icon: 'bi-diagram-3', permission: '*' },
      { label: 'Права доступу (Permissions)', to: '/permissions', icon: 'bi-key', permission: '*' },
    ],
  },
  {
    id: 'catalog',
    label: 'Каталог',
    icon: 'bi-book',
    permission: 'catalog.view',
    items: [
      { label: 'Типи ТЗ',     to: '/catalog/vehicle-types', icon: 'bi-truck',          permission: 'catalog.vehicle-types.view' },
      { label: 'Марки авто',  to: '/catalog/car-brands',    icon: 'bi-car-front',      permission: 'catalog.car-brands.view'    },
      { label: 'Моделі авто', to: '/catalog/car-models',    icon: 'bi-car-front-fill', permission: 'catalog.car-models.view'    },
      { label: 'Групи послуг', to: '/catalog/service-groups', icon: 'bi-collection',     permission: 'catalog.service-groups.view' },
      { label: 'Послуги',     to: '/catalog/services',       icon: 'bi-wrench',         permission: 'catalog.services.view'       },
    ],
  },
  {
    id: 'geography',
    label: 'Географія',
    icon: 'bi-globe-europe-africa',
    permission: 'geography.countries.view',
    items: [
      { label: 'Країни',            to: '/geography/countries',  icon: 'bi-flag',         permission: 'geography.countries.view'   },
      { label: 'Регіони',          to: '/geography/areas',      icon: 'bi-map',          permission: 'geography.regions.view'     },
      { label: 'Райони',           to: '/geography/districts',  icon: 'bi-geo-alt',      permission: 'geography.districts.view'   },
      { label: 'Населені пункти', to: '/geography/cities',     icon: 'bi-building',     permission: 'geography.cities.view'      },
      { label: 'Типи нас. пунктів', to: '/geography/city-types',      icon: 'bi-tags',       permission: 'geography.city_types.view'  },
      { label: 'Нові міста',        to: '/geography/city-tmp-review', icon: 'bi-inbox-fill', permission: 'geography.city_tmp.view'     },
      { label: 'Таймзони',          to: '/geography/timezones',       icon: 'bi-clock',      permission: 'geography.timezones.view'   },
    ],
  },
  {
    id: 'feedback',
    label: 'Зворотній зв\'язок',
    icon: 'bi-chat-left-text',
    permission: 'feedback.view',
    items: [
      { label: 'Новини',              to: '/news',            icon: 'bi-newspaper',      permission: 'news.view' },
      { label: 'Модерація відгуків',   to: '/reviews',         icon: 'bi-check2-circle',  permission: 'reviews.view' },
      { label: 'Список звернень',     to: '/feedback',        icon: 'bi-list-ul',        permission: 'feedback.view' },
      { label: 'Статистика звернень', to: '/feedback/stats',  icon: 'bi-bar-chart',      permission: 'feedback.view' },
    ],
  },
  {
    id: 'analytics',
    label: 'Аналітика',
    icon: 'bi-graph-up',
    permission: 'analytics.view',
    items: [
      { label: 'Відвідування', to: '/analytics',        icon: 'bi-eye',         permission: 'analytics.view' },
      { label: 'Статистика',   to: '/analytics/stats',  icon: 'bi-bar-chart',   permission: 'analytics.view' },
      { label: 'Графіки',      to: '/analytics/charts', icon: 'bi-graph-up-arrow', permission: 'analytics.view' },
      { label: 'Заблоковані IP', to: '/analytics/banned-ips', icon: 'bi-shield-slash', permission: 'analytics.view' },
    ],
  },
  {
    id: 'system',
    label: 'Система',
    icon: 'bi-gear',
    permission: 'logs.view',
    items: [
      { label: 'Логи помилок',  to: '/error-logs',       icon: 'bi-bug',         permission: 'logs.view' },
      { label: 'Статистика помилок', to: '/error-logs/stats', icon: 'bi-exclamation-triangle', permission: 'logs.view' },
      { label: 'Моніторинг',    to: '/system/monitor',   icon: 'bi-hdd-network', permission: 'system.monitoring.view' },
    ],
  },
  {
    id: 'dev',
    label: 'Dev Tools',
    icon: 'bi-code-slash',
    permission: 'api.documentation.view',
    items: [
      { label: 'API Docs (Admin)', to: '/api-docs-admin', icon: 'bi-book', permission: 'api.documentation.view' },
    ],
  },
]
